image: docker:latest

stages:
  - build
  - test
  - lint
  - security
  - dast
  - deploy
  - monitor

variables:
  DOCKER_REGISTRY: registry.gitlab.com/zaunior/HackersdoBem
  IMAGE_NAME: my-app
  GRAFANA_URL: http://localhost:3100
  GRAFANA_USER: admin
  GRAFANA_PASSWORD: admin
  LOKI_URL: http://localhost:3100

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$CI_PIPELINE_ID .

test:
  stage: test
  script:
    - pytest

lint:
  stage: lint
  script:
    - flake8  # Exemplo de ferramenta de lint para Python
    - isort  # Para organizar as importações

security:
  stage: security
  script:
    - bandit -r . -f json -o bandit_report.json
    - dependency-check.sh --project "my-project" --scan . --format ALL

dast:
  stage: dast
  image: zaproxy/zap-stable:2.15.0
  services:
    - name: docker:dind
      command: ["--host=unix:///var/run/docker.sock"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker run -d --name my-app -p 5000:5000 $DOCKER_REGISTRY/$IMAGE_NAME:$CI_PIPELINE_ID
    - docker run -d --name zap -p 8080:8080 zaproxy/zap-stable:2.15.0 zap.sh -daemon -host 0.0.0.0 -port 8080
    - sleep 30
    - docker exec zap zap-cli quick-scan -t http://localhost:5000 -r zap_report.html || true
  artifacts:
    paths:
      - zap_report.html
    expire_in: 1 week

monitor:
  stage: monitor
  script:
    - |
      curl -X POST -H "Content-Type: application/json" -d '{
        "name": "Loki",
        "type": "loki",
        "url": "'"$LOKI_URL"'",
        "access": "proxy"
      }' http://"$GRAFANA_USER":"$GRAFANA_PASSWORD"@"$GRAFANA_URL"/api/datasources || true

