image: python:3.9-slim-buster

variables:
  BASE_URL: "http://127.0.0.1:5000"  # URL da sua aplicação Flask em desenvolvimento
  ENVIRONMENT: "development"           # Indica que está em desenvolvimento

stages:
  - build
  - test
  - lint

before_script:
  - pip install --cache-dir /tmp/pip_cache -r requirements.txt

build:
  stage: build
  script:
    - echo "Build stage: Executando processos de build..."

test:
  stage: test
  script:
    - pytest  # Executar testes

lint:
  stage: lint
  script:
    - pip install flake8 isort  # Instalar ferramentas de lint
    - flake8 .  # Executar flake8
    - isort . --check-only  # Verificar importações

